Repository Sulaimannabdul/Linktree-2.0-maybe, pull requests merged in 2024-03, with the labels that each got.

#3 loop
  packagelock.json
Labels: duplicate

#5 AldineFont
  pages/app.tsx
Labels: documentation

#6 MultipleConfAdd
  packagelock.json
Labels: bug, documentation, duplicate

#7 Create links.json
  dist/links.json
Labels: documentation, duplicate

#8 LinksConfig+
  dist/links.json
Labels: documentation, duplicate

#10 Version 1.2
  packagelock.json
Labels: dependencies

#11 loop
  dist/links.json
Labels: documentation, dependencies

#13 null=false
  utils/twitter.ts
Labels: documentation
